### ISSUE TITLE
如何根据时间来检索资源？

### ISSUE THREAD

**Issue by ludashi2020** [Bmixo/btSearch#11]
没看到有这个选项？

**Comment by Bmixo** [comment]
![Uploading F59FBE16-DC68-49E5-A4F1-0DA21E14461A.png…]()

**Comment by Bmixo** [comment]
![a697905b2d1a2317934f18e8302c5c8](https://user-images.githubusercontent.com/25509024/170022635-9ad26667-fc44-4c4f-9c0b-7283250d0002.png)
