### ISSUE TITLE
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by ludashi2020** [Bmixo/btSearch#5]
执行这个命令mongo-connector -m mongodb://127.0.0.1:27017/?unicode_decode_error_handler=ignore -t http://elastic:changeme@127.0.0.1:9200/torrent -d elastic2_doc_manager -n bavbt.torrent -i name,length,hot,create_time,category,infohash
的时候报错了
`pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 61dea303535586daad64f933, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>`

**Comment by Bmixo** [comment]
可能是各组件运行情况或者组件间的版本依赖问题吧，建议你看下源码解决，未来我会发布一个一键运行的docker镜像和k8s 搭建高可用节点的一套方案
