### ISSUE TITLE
web运行报错

### ISSUE THREAD

**Issue by ludashi2020** [Bmixo/btSearch#6]
root@debian:/home/wwwroot/btSearch# go run main.go
2022/02/11 19:40:33 Error getting response: unsupported protocol scheme ""
exit status 1

貌似缺少环境变量

web端旧版本是有配置文件的，新版应该怎么设置呢？

**Comment by Bmixo** [comment]
设置以下环境变量
    mongoAddr=127.0.0.1:27017
    mongoDatabase=bavbt
    mongoCollection=torrent
    mongoUsername=root
    mongoPassWord=root
    esUsername=elastic
    esPassWord=changeme
    esURL=http://127.0.0.1:9200/bavbt/torrent/
    esUrlBase=http://127.0.0.1:9200
    webServerAddr=127.0.0.1:7878
