### ISSUE TITLE
web端口没有运行起来

### ISSUE THREAD

**Issue by ludashi2020** [Bmixo/btSearch#7]
环境变量已经设置好了，这次没有报错了，但是web没有启动成功，不知道是哪里的问题。求指点。谢谢
root@debian:/home/wwwroot/btSearch# go run main.go
2022/02/15 10:59:22 [200 OK] {
  "name" : "qRF7gqv",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "aYjNHqpQQYKhzriQif8dWQ",
  "version" : {
    "number" : "5.6.0",
    "build_hash" : "781a835",
    "build_date" : "2017-09-07T03:09:58.087Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  },
  "tagline" : "You Know, for Search"
}

7878端口并没有被监听

**Comment by ludashi2020** [comment]
我是按在文档安装说明操作的，不知道问题出在哪里？也没有报错日志

**Comment by Bmixo** [comment]
前段时间，我试过按文档安装没有问题的，可以检查下系统环境方面问题吧，我下个版本会提供一个docker一键运行镜像，如果解决不了，请耐心等待
